{% set name = "dict_hash" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dict_hash-{{ version }}.tar.gz
  sha256: 57dd361a9a3345ce9fae914327f2e51d0ebe40a48dbf5238eb078786bdcb03ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - deflate_dict >=1.0.8
    - support_developer >=1.0.4

test:
  imports:
    - dict_hash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/dict_hash
  summary: Simple python tool to hash dictionaries using both default hash and sha256.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
